{
 "title": "Robot Framework Grafana Dashboard",
 "description": "Robot Framework Test Results Grafana Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "build_no",
    "label": "Build No",
    "query": "SELECT build_number FROM \"autogen\".\"rf_results\" WHERE (\"project_name\"='$project_name' ) "
   },
   {
    "name": "project_name",
    "query": "SELECT \"project_name\" FROM \"rf_results\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Automation Execution Status - Build No",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Passed",
     "measurement": "rf_results",
     "query": "SELECT \"rf_passed\" FROM \"autogen\".\"rf_results\" WHERE (\"project_path\"='$project_name' AND \"build_number\" = $build_no) ",
     "select": [
      [
       { "params": [ "rf_failed" ], "type": "field" }
      ],
      [
       { "params": [ "rf_passed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rf_failed\" FROM \"autogen\".\"rf_results\" WHERE (\"project_path\"='$project_name' AND \"build_number\" = $build_no) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_results",
     "query": "SELECT count(\"rf_total\") FROM \"autogen\".\"rf_results\" WHERE (\"project_name\"='$project_name')",
     "select": [
      [
       { "params": [ "rf_total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "Avg Success Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "rf_results",
     "query": "SELECT mean(\"rf_pass_percentage\") FROM \"autogen\".\"rf_results\"WHERE (\"project_name\"='$project_name') AND $timeFilter",
     "select": [
      [
       { "params": [ "rf_pass_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "EMTE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_results",
     "query": "SELECT sum(\"rf_duration\") FROM \"autogen\".\"rf_results\" WHERE (\"project_name\"='$project_name')",
     "select": [
      [
       { "params": [ "rf_total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "Avg Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_results",
     "query": "SELECT mean(\"rf_duration\") FROM \"autogen\".\"rf_results\" WHERE (\"project_name\"='$project_name')",
     "select": [
      [
       { "params": [ "rf_total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "All Executions - Build No",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rf_suite_name\",\"rf_passed\", \"rf_failed\", \"rf_duration\" FROM \"autogen\".\"suite_result\" WHERE (\"project_name\"='$project_name' AND \"build_number\" = $build_no)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Failed Tests Details",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "rf_name" ], "type": "tag" }
     ],
     "measurement": "testcase_point",
     "query": "SELECT sum(\"rf_failed\") FROM \"autogen\".\"testcase_point\" WHERE (\"project_name\"='$project_name') AND $timeFilter GROUP BY \"rf_name\"",
     "select": [
      [
       { "params": [ "rf_failed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "Automation Test Execution Trend",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "TC Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rf_passed\", \"rf_failed\", \"rf_total\" FROM \"autogen\".\"rf_results\" WHERE (\"project_name\"='$project_name') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}